/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GrantProgramInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "applyForGrant"
      | "approveApplications"
      | "cancelGrant"
      | "claimGrant"
      | "createGrant"
      | "finalizeSelection"
      | "getApplication"
      | "getApplicationCount"
      | "getGrantInfo"
      | "getRecipientAmount"
      | "getSelectedRecipients"
      | "getUpdate"
      | "getUpdateCount"
      | "grantCounter"
      | "grants"
      | "hasApplied"
      | "hasClaimedGrant"
      | "nftAddress"
      | "owner"
      | "postUpdate"
      | "rejectApplications"
      | "renounceOwnership"
      | "setNFTAddress"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApplicationApproved"
      | "ApplicationRejected"
      | "ApplicationSubmitted"
      | "FundsClaimed"
      | "GrantCancelled"
      | "GrantCompleted"
      | "GrantCreated"
      | "OwnershipTransferred"
      | "UpdatePosted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "applyForGrant",
    values: [BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveApplications",
    values: [BigNumberish, BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelGrant",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimGrant",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createGrant",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeSelection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApplication",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApplicationCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGrantInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecipientAmount",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSelectedRecipients",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUpdate",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUpdateCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApplied",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimedGrant",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nftAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postUpdate",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectApplications",
    values: [BigNumberish, BigNumberish[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setNFTAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "applyForGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimGrant", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeSelection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApplication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApplicationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGrantInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecipientAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSelectedRecipients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUpdate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUpdateCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grants", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasApplied", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasClaimedGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nftAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postUpdate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rejectApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNFTAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ApplicationApprovedEvent {
  export type InputTuple = [
    grantId: BigNumberish,
    applicationId: BigNumberish,
    applicant: AddressLike,
    approvedAmount: BigNumberish
  ];
  export type OutputTuple = [
    grantId: bigint,
    applicationId: bigint,
    applicant: string,
    approvedAmount: bigint
  ];
  export interface OutputObject {
    grantId: bigint;
    applicationId: bigint;
    applicant: string;
    approvedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApplicationRejectedEvent {
  export type InputTuple = [
    grantId: BigNumberish,
    applicationId: BigNumberish,
    applicant: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    grantId: bigint,
    applicationId: bigint,
    applicant: string,
    reason: string
  ];
  export interface OutputObject {
    grantId: bigint;
    applicationId: bigint;
    applicant: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApplicationSubmittedEvent {
  export type InputTuple = [
    grantId: BigNumberish,
    applicationId: BigNumberish,
    applicant: AddressLike,
    requestedAmount: BigNumberish
  ];
  export type OutputTuple = [
    grantId: bigint,
    applicationId: bigint,
    applicant: string,
    requestedAmount: bigint
  ];
  export interface OutputObject {
    grantId: bigint;
    applicationId: bigint;
    applicant: string;
    requestedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsClaimedEvent {
  export type InputTuple = [
    grantId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    grantId: bigint,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    grantId: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GrantCancelledEvent {
  export type InputTuple = [grantId: BigNumberish, refundAmount: BigNumberish];
  export type OutputTuple = [grantId: bigint, refundAmount: bigint];
  export interface OutputObject {
    grantId: bigint;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GrantCompletedEvent {
  export type InputTuple = [
    grantId: BigNumberish,
    totalDistributed: BigNumberish
  ];
  export type OutputTuple = [grantId: bigint, totalDistributed: bigint];
  export interface OutputObject {
    grantId: bigint;
    totalDistributed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GrantCreatedEvent {
  export type InputTuple = [
    grantId: BigNumberish,
    giver: AddressLike,
    title: string,
    totalFunds: BigNumberish,
    applicationDeadline: BigNumberish
  ];
  export type OutputTuple = [
    grantId: bigint,
    giver: string,
    title: string,
    totalFunds: bigint,
    applicationDeadline: bigint
  ];
  export interface OutputObject {
    grantId: bigint;
    giver: string;
    title: string;
    totalFunds: bigint;
    applicationDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatePostedEvent {
  export type InputTuple = [
    grantId: BigNumberish,
    author: AddressLike,
    content: string
  ];
  export type OutputTuple = [grantId: bigint, author: string, content: string];
  export interface OutputObject {
    grantId: bigint;
    author: string;
    content: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GrantProgram extends BaseContract {
  connect(runner?: ContractRunner | null): GrantProgram;
  waitForDeployment(): Promise<this>;

  interface: GrantProgramInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applyForGrant: TypedContractMethod<
    [
      _grantId: BigNumberish,
      _projectDetails: string,
      _socialAccounts: string,
      _requestedAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  approveApplications: TypedContractMethod<
    [
      _grantId: BigNumberish,
      _applicationIds: BigNumberish[],
      _approvedAmounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  cancelGrant: TypedContractMethod<
    [_grantId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimGrant: TypedContractMethod<
    [_grantId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createGrant: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _maxApplicants: BigNumberish,
      _applicationDeadline: BigNumberish,
      _distributionDeadline: BigNumberish
    ],
    [void],
    "payable"
  >;

  finalizeSelection: TypedContractMethod<
    [_grantId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getApplication: TypedContractMethod<
    [_grantId: BigNumberish, _appId: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, string] & {
        applicant: string;
        projectDetails: string;
        socialAccounts: string;
        requestedAmount: bigint;
        appliedAt: bigint;
        status: bigint;
        rejectionReason: string;
      }
    ],
    "view"
  >;

  getApplicationCount: TypedContractMethod<
    [_grantId: BigNumberish],
    [bigint],
    "view"
  >;

  getGrantInfo: TypedContractMethod<
    [_grantId: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        giver: string;
        title: string;
        description: string;
        totalFunds: bigint;
        maxApplicants: bigint;
        applicationDeadline: bigint;
        distributionDeadline: bigint;
        status: bigint;
        fundsDistributed: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getRecipientAmount: TypedContractMethod<
    [_grantId: BigNumberish, _recipient: AddressLike],
    [bigint],
    "view"
  >;

  getSelectedRecipients: TypedContractMethod<
    [_grantId: BigNumberish],
    [string[]],
    "view"
  >;

  getUpdate: TypedContractMethod<
    [_grantId: BigNumberish, _updateId: BigNumberish],
    [
      [string, string, bigint] & {
        author: string;
        content: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getUpdateCount: TypedContractMethod<
    [_grantId: BigNumberish],
    [bigint],
    "view"
  >;

  grantCounter: TypedContractMethod<[], [bigint], "view">;

  grants: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        giver: string;
        title: string;
        description: string;
        totalFunds: bigint;
        maxApplicants: bigint;
        applicationDeadline: bigint;
        distributionDeadline: bigint;
        status: bigint;
        fundsDistributed: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  hasApplied: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasClaimedGrant: TypedContractMethod<
    [_grantId: BigNumberish, _recipient: AddressLike],
    [boolean],
    "view"
  >;

  nftAddress: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  postUpdate: TypedContractMethod<
    [_grantId: BigNumberish, _content: string],
    [void],
    "nonpayable"
  >;

  rejectApplications: TypedContractMethod<
    [
      _grantId: BigNumberish,
      _applicationIds: BigNumberish[],
      _reasons: string[]
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setNFTAddress: TypedContractMethod<
    [_nftAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applyForGrant"
  ): TypedContractMethod<
    [
      _grantId: BigNumberish,
      _projectDetails: string,
      _socialAccounts: string,
      _requestedAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveApplications"
  ): TypedContractMethod<
    [
      _grantId: BigNumberish,
      _applicationIds: BigNumberish[],
      _approvedAmounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelGrant"
  ): TypedContractMethod<[_grantId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimGrant"
  ): TypedContractMethod<[_grantId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createGrant"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _maxApplicants: BigNumberish,
      _applicationDeadline: BigNumberish,
      _distributionDeadline: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "finalizeSelection"
  ): TypedContractMethod<[_grantId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getApplication"
  ): TypedContractMethod<
    [_grantId: BigNumberish, _appId: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, string] & {
        applicant: string;
        projectDetails: string;
        socialAccounts: string;
        requestedAmount: bigint;
        appliedAt: bigint;
        status: bigint;
        rejectionReason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getApplicationCount"
  ): TypedContractMethod<[_grantId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGrantInfo"
  ): TypedContractMethod<
    [_grantId: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        giver: string;
        title: string;
        description: string;
        totalFunds: bigint;
        maxApplicants: bigint;
        applicationDeadline: bigint;
        distributionDeadline: bigint;
        status: bigint;
        fundsDistributed: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecipientAmount"
  ): TypedContractMethod<
    [_grantId: BigNumberish, _recipient: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSelectedRecipients"
  ): TypedContractMethod<[_grantId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUpdate"
  ): TypedContractMethod<
    [_grantId: BigNumberish, _updateId: BigNumberish],
    [
      [string, string, bigint] & {
        author: string;
        content: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUpdateCount"
  ): TypedContractMethod<[_grantId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grants"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        giver: string;
        title: string;
        description: string;
        totalFunds: bigint;
        maxApplicants: bigint;
        applicationDeadline: bigint;
        distributionDeadline: bigint;
        status: bigint;
        fundsDistributed: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasApplied"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimedGrant"
  ): TypedContractMethod<
    [_grantId: BigNumberish, _recipient: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nftAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postUpdate"
  ): TypedContractMethod<
    [_grantId: BigNumberish, _content: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectApplications"
  ): TypedContractMethod<
    [
      _grantId: BigNumberish,
      _applicationIds: BigNumberish[],
      _reasons: string[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setNFTAddress"
  ): TypedContractMethod<[_nftAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ApplicationApproved"
  ): TypedContractEvent<
    ApplicationApprovedEvent.InputTuple,
    ApplicationApprovedEvent.OutputTuple,
    ApplicationApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ApplicationRejected"
  ): TypedContractEvent<
    ApplicationRejectedEvent.InputTuple,
    ApplicationRejectedEvent.OutputTuple,
    ApplicationRejectedEvent.OutputObject
  >;
  getEvent(
    key: "ApplicationSubmitted"
  ): TypedContractEvent<
    ApplicationSubmittedEvent.InputTuple,
    ApplicationSubmittedEvent.OutputTuple,
    ApplicationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "FundsClaimed"
  ): TypedContractEvent<
    FundsClaimedEvent.InputTuple,
    FundsClaimedEvent.OutputTuple,
    FundsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "GrantCancelled"
  ): TypedContractEvent<
    GrantCancelledEvent.InputTuple,
    GrantCancelledEvent.OutputTuple,
    GrantCancelledEvent.OutputObject
  >;
  getEvent(
    key: "GrantCompleted"
  ): TypedContractEvent<
    GrantCompletedEvent.InputTuple,
    GrantCompletedEvent.OutputTuple,
    GrantCompletedEvent.OutputObject
  >;
  getEvent(
    key: "GrantCreated"
  ): TypedContractEvent<
    GrantCreatedEvent.InputTuple,
    GrantCreatedEvent.OutputTuple,
    GrantCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UpdatePosted"
  ): TypedContractEvent<
    UpdatePostedEvent.InputTuple,
    UpdatePostedEvent.OutputTuple,
    UpdatePostedEvent.OutputObject
  >;

  filters: {
    "ApplicationApproved(uint256,uint256,address,uint256)": TypedContractEvent<
      ApplicationApprovedEvent.InputTuple,
      ApplicationApprovedEvent.OutputTuple,
      ApplicationApprovedEvent.OutputObject
    >;
    ApplicationApproved: TypedContractEvent<
      ApplicationApprovedEvent.InputTuple,
      ApplicationApprovedEvent.OutputTuple,
      ApplicationApprovedEvent.OutputObject
    >;

    "ApplicationRejected(uint256,uint256,address,string)": TypedContractEvent<
      ApplicationRejectedEvent.InputTuple,
      ApplicationRejectedEvent.OutputTuple,
      ApplicationRejectedEvent.OutputObject
    >;
    ApplicationRejected: TypedContractEvent<
      ApplicationRejectedEvent.InputTuple,
      ApplicationRejectedEvent.OutputTuple,
      ApplicationRejectedEvent.OutputObject
    >;

    "ApplicationSubmitted(uint256,uint256,address,uint256)": TypedContractEvent<
      ApplicationSubmittedEvent.InputTuple,
      ApplicationSubmittedEvent.OutputTuple,
      ApplicationSubmittedEvent.OutputObject
    >;
    ApplicationSubmitted: TypedContractEvent<
      ApplicationSubmittedEvent.InputTuple,
      ApplicationSubmittedEvent.OutputTuple,
      ApplicationSubmittedEvent.OutputObject
    >;

    "FundsClaimed(uint256,address,uint256)": TypedContractEvent<
      FundsClaimedEvent.InputTuple,
      FundsClaimedEvent.OutputTuple,
      FundsClaimedEvent.OutputObject
    >;
    FundsClaimed: TypedContractEvent<
      FundsClaimedEvent.InputTuple,
      FundsClaimedEvent.OutputTuple,
      FundsClaimedEvent.OutputObject
    >;

    "GrantCancelled(uint256,uint256)": TypedContractEvent<
      GrantCancelledEvent.InputTuple,
      GrantCancelledEvent.OutputTuple,
      GrantCancelledEvent.OutputObject
    >;
    GrantCancelled: TypedContractEvent<
      GrantCancelledEvent.InputTuple,
      GrantCancelledEvent.OutputTuple,
      GrantCancelledEvent.OutputObject
    >;

    "GrantCompleted(uint256,uint256)": TypedContractEvent<
      GrantCompletedEvent.InputTuple,
      GrantCompletedEvent.OutputTuple,
      GrantCompletedEvent.OutputObject
    >;
    GrantCompleted: TypedContractEvent<
      GrantCompletedEvent.InputTuple,
      GrantCompletedEvent.OutputTuple,
      GrantCompletedEvent.OutputObject
    >;

    "GrantCreated(uint256,address,string,uint256,uint256)": TypedContractEvent<
      GrantCreatedEvent.InputTuple,
      GrantCreatedEvent.OutputTuple,
      GrantCreatedEvent.OutputObject
    >;
    GrantCreated: TypedContractEvent<
      GrantCreatedEvent.InputTuple,
      GrantCreatedEvent.OutputTuple,
      GrantCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UpdatePosted(uint256,address,string)": TypedContractEvent<
      UpdatePostedEvent.InputTuple,
      UpdatePostedEvent.OutputTuple,
      UpdatePostedEvent.OutputObject
    >;
    UpdatePosted: TypedContractEvent<
      UpdatePostedEvent.InputTuple,
      UpdatePostedEvent.OutputTuple,
      UpdatePostedEvent.OutputObject
    >;
  };
}
