/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as quintySol from "./Quinty.sol";
export type { quintySol };
export type { AirdropBounty } from "./AirdropBounty";
export type { Counter } from "./Counter";
export type { DisputeResolver } from "./DisputeResolver";
export type { QuintyReputation } from "./QuintyReputation";
