/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface QuestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelQuest"
      | "createQuest"
      | "entries"
      | "finalizeQuest"
      | "getEntry"
      | "getEntryCount"
      | "getQuest"
      | "getQuestStats"
      | "getSocialAccount"
      | "getUserSubmission"
      | "hasSubmitted"
      | "linkSocialAccount"
      | "owner"
      | "questCounter"
      | "quests"
      | "renounceOwnership"
      | "socialAccounts"
      | "submitEntry"
      | "transferOwnership"
      | "userSubmissionIndex"
      | "verifyEntry"
      | "verifyMultipleEntries"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EntrySubmitted"
      | "EntryVerified"
      | "OwnershipTransferred"
      | "QuestCancelled"
      | "QuestCreated"
      | "QuestFinalized"
      | "SocialAccountLinked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelQuest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createQuest",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "entries",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeQuest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntry",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuestStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSocialAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSubmission",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "linkSocialAccount",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "questCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "socialAccounts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEntry",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userSubmissionIndex",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEntry",
    values: [BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMultipleEntries",
    values: [BigNumberish, BigNumberish[], BigNumberish[], string[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entries", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEntry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getQuest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getQuestStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSocialAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "linkSocialAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "questCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "socialAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userSubmissionIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyMultipleEntries",
    data: BytesLike
  ): Result;
}

export namespace EntrySubmittedEvent {
  export type InputTuple = [
    id: BigNumberish,
    solver: AddressLike,
    ipfsProofCid: string,
    socialHandle: string
  ];
  export type OutputTuple = [
    id: bigint,
    solver: string,
    ipfsProofCid: string,
    socialHandle: string
  ];
  export interface OutputObject {
    id: bigint;
    solver: string;
    ipfsProofCid: string;
    socialHandle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntryVerifiedEvent {
  export type InputTuple = [
    questId: BigNumberish,
    entryId: BigNumberish,
    verifier: AddressLike,
    status: BigNumberish
  ];
  export type OutputTuple = [
    questId: bigint,
    entryId: bigint,
    verifier: string,
    status: bigint
  ];
  export interface OutputObject {
    questId: bigint;
    entryId: bigint;
    verifier: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestCancelledEvent {
  export type InputTuple = [id: BigNumberish, refundAmount: BigNumberish];
  export type OutputTuple = [id: bigint, refundAmount: bigint];
  export interface OutputObject {
    id: bigint;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    title: string,
    perQualifier: BigNumberish,
    maxQualifiers: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    creator: string,
    title: string,
    perQualifier: bigint,
    maxQualifiers: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    id: bigint;
    creator: string;
    title: string;
    perQualifier: bigint;
    maxQualifiers: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestFinalizedEvent {
  export type InputTuple = [
    id: BigNumberish,
    qualifiers: AddressLike[],
    totalDistributed: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    qualifiers: string[],
    totalDistributed: bigint
  ];
  export interface OutputObject {
    id: bigint;
    qualifiers: string[];
    totalDistributed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SocialAccountLinkedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    xHandle: string,
    email: string
  ];
  export type OutputTuple = [wallet: string, xHandle: string, email: string];
  export interface OutputObject {
    wallet: string;
    xHandle: string;
    email: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Quest extends BaseContract {
  connect(runner?: ContractRunner | null): Quest;
  waitForDeployment(): Promise<this>;

  interface: QuestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelQuest: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  createQuest: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _perQualifier: BigNumberish,
      _maxQualifiers: BigNumberish,
      _deadline: BigNumberish,
      _requirements: string
    ],
    [void],
    "payable"
  >;

  entries: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, string, bigint, bigint, string] & {
        solver: string;
        ipfsProofCid: string;
        socialHandle: string;
        timestamp: bigint;
        status: bigint;
        feedback: string;
      }
    ],
    "view"
  >;

  finalizeQuest: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  getEntry: TypedContractMethod<
    [_questId: BigNumberish, _entryId: BigNumberish],
    [
      [string, string, string, bigint, bigint, string] & {
        solver: string;
        ipfsProofCid: string;
        socialHandle: string;
        timestamp: bigint;
        status: bigint;
        feedback: string;
      }
    ],
    "view"
  >;

  getEntryCount: TypedContractMethod<
    [_questId: BigNumberish],
    [bigint],
    "view"
  >;

  getQuest: TypedContractMethod<
    [_id: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        creator: string;
        title: string;
        description: string;
        totalAmount: bigint;
        perQualifier: bigint;
        maxQualifiers: bigint;
        qualifiersCount: bigint;
        deadline: bigint;
        createdAt: bigint;
        resolved: boolean;
        cancelled: boolean;
        requirements: string;
      }
    ],
    "view"
  >;

  getQuestStats: TypedContractMethod<
    [_questId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalEntries: bigint;
        pendingEntries: bigint;
        approvedEntries: bigint;
        rejectedEntries: bigint;
        remainingSlots: bigint;
      }
    ],
    "view"
  >;

  getSocialAccount: TypedContractMethod<
    [_wallet: AddressLike],
    [
      [string, string, bigint, boolean] & {
        xHandle: string;
        email: string;
        linkedAt: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;

  getUserSubmission: TypedContractMethod<
    [_questId: BigNumberish, _user: AddressLike],
    [
      [boolean, bigint, bigint] & {
        hasSubmittedEntry: boolean;
        submissionIndex: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  hasSubmitted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  linkSocialAccount: TypedContractMethod<
    [_xHandle: string, _email: string],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  questCounter: TypedContractMethod<[], [bigint], "view">;

  quests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        creator: string;
        title: string;
        description: string;
        totalAmount: bigint;
        perQualifier: bigint;
        maxQualifiers: bigint;
        qualifiersCount: bigint;
        deadline: bigint;
        createdAt: bigint;
        resolved: boolean;
        cancelled: boolean;
        requirements: string;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  socialAccounts: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean] & {
        xHandle: string;
        email: string;
        linkedAt: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;

  submitEntry: TypedContractMethod<
    [_id: BigNumberish, _ipfsProofCid: string, _socialHandle: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userSubmissionIndex: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  verifyEntry: TypedContractMethod<
    [
      _questId: BigNumberish,
      _entryId: BigNumberish,
      _status: BigNumberish,
      _feedback: string
    ],
    [void],
    "nonpayable"
  >;

  verifyMultipleEntries: TypedContractMethod<
    [
      _questId: BigNumberish,
      _entryIds: BigNumberish[],
      _statuses: BigNumberish[],
      _feedbacks: string[]
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelQuest"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createQuest"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _perQualifier: BigNumberish,
      _maxQualifiers: BigNumberish,
      _deadline: BigNumberish,
      _requirements: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "entries"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, string, bigint, bigint, string] & {
        solver: string;
        ipfsProofCid: string;
        socialHandle: string;
        timestamp: bigint;
        status: bigint;
        feedback: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "finalizeQuest"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEntry"
  ): TypedContractMethod<
    [_questId: BigNumberish, _entryId: BigNumberish],
    [
      [string, string, string, bigint, bigint, string] & {
        solver: string;
        ipfsProofCid: string;
        socialHandle: string;
        timestamp: bigint;
        status: bigint;
        feedback: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntryCount"
  ): TypedContractMethod<[_questId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getQuest"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        creator: string;
        title: string;
        description: string;
        totalAmount: bigint;
        perQualifier: bigint;
        maxQualifiers: bigint;
        qualifiersCount: bigint;
        deadline: bigint;
        createdAt: bigint;
        resolved: boolean;
        cancelled: boolean;
        requirements: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getQuestStats"
  ): TypedContractMethod<
    [_questId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalEntries: bigint;
        pendingEntries: bigint;
        approvedEntries: bigint;
        rejectedEntries: bigint;
        remainingSlots: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSocialAccount"
  ): TypedContractMethod<
    [_wallet: AddressLike],
    [
      [string, string, bigint, boolean] & {
        xHandle: string;
        email: string;
        linkedAt: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserSubmission"
  ): TypedContractMethod<
    [_questId: BigNumberish, _user: AddressLike],
    [
      [boolean, bigint, bigint] & {
        hasSubmittedEntry: boolean;
        submissionIndex: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "linkSocialAccount"
  ): TypedContractMethod<
    [_xHandle: string, _email: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "questCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "quests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        creator: string;
        title: string;
        description: string;
        totalAmount: bigint;
        perQualifier: bigint;
        maxQualifiers: bigint;
        qualifiersCount: bigint;
        deadline: bigint;
        createdAt: bigint;
        resolved: boolean;
        cancelled: boolean;
        requirements: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "socialAccounts"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean] & {
        xHandle: string;
        email: string;
        linkedAt: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitEntry"
  ): TypedContractMethod<
    [_id: BigNumberish, _ipfsProofCid: string, _socialHandle: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userSubmissionIndex"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyEntry"
  ): TypedContractMethod<
    [
      _questId: BigNumberish,
      _entryId: BigNumberish,
      _status: BigNumberish,
      _feedback: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyMultipleEntries"
  ): TypedContractMethod<
    [
      _questId: BigNumberish,
      _entryIds: BigNumberish[],
      _statuses: BigNumberish[],
      _feedbacks: string[]
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EntrySubmitted"
  ): TypedContractEvent<
    EntrySubmittedEvent.InputTuple,
    EntrySubmittedEvent.OutputTuple,
    EntrySubmittedEvent.OutputObject
  >;
  getEvent(
    key: "EntryVerified"
  ): TypedContractEvent<
    EntryVerifiedEvent.InputTuple,
    EntryVerifiedEvent.OutputTuple,
    EntryVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "QuestCancelled"
  ): TypedContractEvent<
    QuestCancelledEvent.InputTuple,
    QuestCancelledEvent.OutputTuple,
    QuestCancelledEvent.OutputObject
  >;
  getEvent(
    key: "QuestCreated"
  ): TypedContractEvent<
    QuestCreatedEvent.InputTuple,
    QuestCreatedEvent.OutputTuple,
    QuestCreatedEvent.OutputObject
  >;
  getEvent(
    key: "QuestFinalized"
  ): TypedContractEvent<
    QuestFinalizedEvent.InputTuple,
    QuestFinalizedEvent.OutputTuple,
    QuestFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "SocialAccountLinked"
  ): TypedContractEvent<
    SocialAccountLinkedEvent.InputTuple,
    SocialAccountLinkedEvent.OutputTuple,
    SocialAccountLinkedEvent.OutputObject
  >;

  filters: {
    "EntrySubmitted(uint256,address,string,string)": TypedContractEvent<
      EntrySubmittedEvent.InputTuple,
      EntrySubmittedEvent.OutputTuple,
      EntrySubmittedEvent.OutputObject
    >;
    EntrySubmitted: TypedContractEvent<
      EntrySubmittedEvent.InputTuple,
      EntrySubmittedEvent.OutputTuple,
      EntrySubmittedEvent.OutputObject
    >;

    "EntryVerified(uint256,uint256,address,uint8)": TypedContractEvent<
      EntryVerifiedEvent.InputTuple,
      EntryVerifiedEvent.OutputTuple,
      EntryVerifiedEvent.OutputObject
    >;
    EntryVerified: TypedContractEvent<
      EntryVerifiedEvent.InputTuple,
      EntryVerifiedEvent.OutputTuple,
      EntryVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "QuestCancelled(uint256,uint256)": TypedContractEvent<
      QuestCancelledEvent.InputTuple,
      QuestCancelledEvent.OutputTuple,
      QuestCancelledEvent.OutputObject
    >;
    QuestCancelled: TypedContractEvent<
      QuestCancelledEvent.InputTuple,
      QuestCancelledEvent.OutputTuple,
      QuestCancelledEvent.OutputObject
    >;

    "QuestCreated(uint256,address,string,uint256,uint256,uint256)": TypedContractEvent<
      QuestCreatedEvent.InputTuple,
      QuestCreatedEvent.OutputTuple,
      QuestCreatedEvent.OutputObject
    >;
    QuestCreated: TypedContractEvent<
      QuestCreatedEvent.InputTuple,
      QuestCreatedEvent.OutputTuple,
      QuestCreatedEvent.OutputObject
    >;

    "QuestFinalized(uint256,address[],uint256)": TypedContractEvent<
      QuestFinalizedEvent.InputTuple,
      QuestFinalizedEvent.OutputTuple,
      QuestFinalizedEvent.OutputObject
    >;
    QuestFinalized: TypedContractEvent<
      QuestFinalizedEvent.InputTuple,
      QuestFinalizedEvent.OutputTuple,
      QuestFinalizedEvent.OutputObject
    >;

    "SocialAccountLinked(address,string,string)": TypedContractEvent<
      SocialAccountLinkedEvent.InputTuple,
      SocialAccountLinkedEvent.OutputTuple,
      SocialAccountLinkedEvent.OutputObject
    >;
    SocialAccountLinked: TypedContractEvent<
      SocialAccountLinkedEvent.InputTuple,
      SocialAccountLinkedEvent.OutputTuple,
      SocialAccountLinkedEvent.OutputObject
    >;
  };
}
