/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IQuintyRegistry {
  export type ContractInfoStruct = {
    contractAddress: AddressLike;
    version: BigNumberish;
    isActive: boolean;
    deployedAt: BigNumberish;
    deprecatedAt: BigNumberish;
  };

  export type ContractInfoStructOutput = [
    contractAddress: string,
    version: bigint,
    isActive: boolean,
    deployedAt: bigint,
    deprecatedAt: bigint
  ] & {
    contractAddress: string;
    version: bigint;
    isActive: boolean;
    deployedAt: bigint;
    deprecatedAt: bigint;
  };
}

export interface QuintyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AIRDROP_BOUNTY"
      | "CROWDFUNDING"
      | "DEFAULT_ADMIN_ROLE"
      | "DISPUTE_RESOLVER"
      | "GRANT_PROGRAM"
      | "LOOKING_FOR_GRANT"
      | "PAUSER_ROLE"
      | "QUINTY"
      | "QUINTY_NFT"
      | "QUINTY_REPUTATION"
      | "SOCIAL_VERIFICATION"
      | "UPGRADER_ROLE"
      | "batchRegisterContracts"
      | "deployedAt"
      | "deprecateContract"
      | "getAllContracts"
      | "getAllVersions"
      | "getContract"
      | "getContractByVersion"
      | "getContractInfo"
      | "getContractTypeId"
      | "getLatestVersion"
      | "getRoleAdmin"
      | "getVersionCount"
      | "grantRole"
      | "hasRole"
      | "isActive"
      | "isPaused"
      | "paused"
      | "registerContract"
      | "renounceRole"
      | "revokeRole"
      | "setPaused"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractDeprecated"
      | "ContractRegistered"
      | "Paused"
      | "ProtocolPaused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AIRDROP_BOUNTY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CROWDFUNDING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISPUTE_RESOLVER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GRANT_PROGRAM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOOKING_FOR_GRANT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "QUINTY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "QUINTY_NFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "QUINTY_REPUTATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOCIAL_VERIFICATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchRegisterContracts",
    values: [BytesLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedAt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deprecateContract",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllVersions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContract",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractByVersion",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractTypeId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestVersion",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVersionCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isActive", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerContract",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "AIRDROP_BOUNTY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CROWDFUNDING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISPUTE_RESOLVER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GRANT_PROGRAM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOOKING_FOR_GRANT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "QUINTY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "QUINTY_NFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "QUINTY_REPUTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOCIAL_VERIFICATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchRegisterContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deployedAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deprecateContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllVersions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractByVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractTypeId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVersionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace ContractDeprecatedEvent {
  export type InputTuple = [
    contractType: BytesLike,
    version: BigNumberish,
    contractAddress: AddressLike
  ];
  export type OutputTuple = [
    contractType: string,
    version: bigint,
    contractAddress: string
  ];
  export interface OutputObject {
    contractType: string;
    version: bigint;
    contractAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractRegisteredEvent {
  export type InputTuple = [
    contractType: BytesLike,
    contractAddress: AddressLike,
    version: BigNumberish,
    previousAddress: AddressLike
  ];
  export type OutputTuple = [
    contractType: string,
    contractAddress: string,
    version: bigint,
    previousAddress: string
  ];
  export interface OutputObject {
    contractType: string;
    contractAddress: string;
    version: bigint;
    previousAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolPausedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface QuintyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): QuintyRegistry;
  waitForDeployment(): Promise<this>;

  interface: QuintyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AIRDROP_BOUNTY: TypedContractMethod<[], [string], "view">;

  CROWDFUNDING: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DISPUTE_RESOLVER: TypedContractMethod<[], [string], "view">;

  GRANT_PROGRAM: TypedContractMethod<[], [string], "view">;

  LOOKING_FOR_GRANT: TypedContractMethod<[], [string], "view">;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  QUINTY: TypedContractMethod<[], [string], "view">;

  QUINTY_NFT: TypedContractMethod<[], [string], "view">;

  QUINTY_REPUTATION: TypedContractMethod<[], [string], "view">;

  SOCIAL_VERIFICATION: TypedContractMethod<[], [string], "view">;

  UPGRADER_ROLE: TypedContractMethod<[], [string], "view">;

  batchRegisterContracts: TypedContractMethod<
    [contractTypes: BytesLike[], contractAddresses: AddressLike[]],
    [void],
    "nonpayable"
  >;

  deployedAt: TypedContractMethod<[], [bigint], "view">;

  deprecateContract: TypedContractMethod<
    [contractType: BytesLike, version: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllContracts: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ] & {
        quinty: string;
        reputation: string;
        nft: string;
        disputeResolver: string;
        grantProgram: string;
        crowdfunding: string;
        lookingForGrant: string;
        airdropBounty: string;
        socialVerification: string;
      }
    ],
    "view"
  >;

  getAllVersions: TypedContractMethod<
    [contractType: BytesLike],
    [string[]],
    "view"
  >;

  getContract: TypedContractMethod<[contractType: BytesLike], [string], "view">;

  getContractByVersion: TypedContractMethod<
    [contractType: BytesLike, version: BigNumberish],
    [string],
    "view"
  >;

  getContractInfo: TypedContractMethod<
    [contractType: BytesLike],
    [IQuintyRegistry.ContractInfoStructOutput],
    "view"
  >;

  getContractTypeId: TypedContractMethod<[name: string], [string], "view">;

  getLatestVersion: TypedContractMethod<
    [contractType: BytesLike],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getVersionCount: TypedContractMethod<
    [contractType: BytesLike],
    [bigint],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isActive: TypedContractMethod<[contractType: BytesLike], [boolean], "view">;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registerContract: TypedContractMethod<
    [contractType: BytesLike, contractAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[_paused: boolean], [void], "nonpayable">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AIRDROP_BOUNTY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CROWDFUNDING"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DISPUTE_RESOLVER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GRANT_PROGRAM"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LOOKING_FOR_GRANT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "QUINTY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "QUINTY_NFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "QUINTY_REPUTATION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SOCIAL_VERIFICATION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "batchRegisterContracts"
  ): TypedContractMethod<
    [contractTypes: BytesLike[], contractAddresses: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployedAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deprecateContract"
  ): TypedContractMethod<
    [contractType: BytesLike, version: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllContracts"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ] & {
        quinty: string;
        reputation: string;
        nft: string;
        disputeResolver: string;
        grantProgram: string;
        crowdfunding: string;
        lookingForGrant: string;
        airdropBounty: string;
        socialVerification: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllVersions"
  ): TypedContractMethod<[contractType: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getContract"
  ): TypedContractMethod<[contractType: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getContractByVersion"
  ): TypedContractMethod<
    [contractType: BytesLike, version: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractInfo"
  ): TypedContractMethod<
    [contractType: BytesLike],
    [IQuintyRegistry.ContractInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractTypeId"
  ): TypedContractMethod<[name: string], [string], "view">;
  getFunction(
    nameOrSignature: "getLatestVersion"
  ): TypedContractMethod<[contractType: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getVersionCount"
  ): TypedContractMethod<[contractType: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[contractType: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerContract"
  ): TypedContractMethod<
    [contractType: BytesLike, contractAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[_paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "ContractDeprecated"
  ): TypedContractEvent<
    ContractDeprecatedEvent.InputTuple,
    ContractDeprecatedEvent.OutputTuple,
    ContractDeprecatedEvent.OutputObject
  >;
  getEvent(
    key: "ContractRegistered"
  ): TypedContractEvent<
    ContractRegisteredEvent.InputTuple,
    ContractRegisteredEvent.OutputTuple,
    ContractRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolPaused"
  ): TypedContractEvent<
    ProtocolPausedEvent.InputTuple,
    ProtocolPausedEvent.OutputTuple,
    ProtocolPausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "ContractDeprecated(bytes32,uint256,address)": TypedContractEvent<
      ContractDeprecatedEvent.InputTuple,
      ContractDeprecatedEvent.OutputTuple,
      ContractDeprecatedEvent.OutputObject
    >;
    ContractDeprecated: TypedContractEvent<
      ContractDeprecatedEvent.InputTuple,
      ContractDeprecatedEvent.OutputTuple,
      ContractDeprecatedEvent.OutputObject
    >;

    "ContractRegistered(bytes32,address,uint256,address)": TypedContractEvent<
      ContractRegisteredEvent.InputTuple,
      ContractRegisteredEvent.OutputTuple,
      ContractRegisteredEvent.OutputObject
    >;
    ContractRegistered: TypedContractEvent<
      ContractRegisteredEvent.InputTuple,
      ContractRegisteredEvent.OutputTuple,
      ContractRegisteredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProtocolPaused(bool)": TypedContractEvent<
      ProtocolPausedEvent.InputTuple,
      ProtocolPausedEvent.OutputTuple,
      ProtocolPausedEvent.OutputObject
    >;
    ProtocolPaused: TypedContractEvent<
      ProtocolPausedEvent.InputTuple,
      ProtocolPausedEvent.OutputTuple,
      ProtocolPausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
