/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IQuintyReputationInterface extends Interface {
  getFunction(
    nameOrSignature: "updateCreatorRep" | "updateSolverRep"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "updateCreatorRep",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSolverRep",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "updateCreatorRep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSolverRep",
    data: BytesLike
  ): Result;
}

export interface IQuintyReputation extends BaseContract {
  connect(runner?: ContractRunner | null): IQuintyReputation;
  waitForDeployment(): Promise<this>;

  interface: IQuintyReputationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  updateCreatorRep: TypedContractMethod<
    [_user: AddressLike, _success: boolean],
    [void],
    "nonpayable"
  >;

  updateSolverRep: TypedContractMethod<
    [_user: AddressLike, _success: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "updateCreatorRep"
  ): TypedContractMethod<
    [_user: AddressLike, _success: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateSolverRep"
  ): TypedContractMethod<
    [_user: AddressLike, _success: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
