/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IQuintyRegistry {
  export type ContractInfoStruct = {
    contractAddress: AddressLike;
    version: BigNumberish;
    isActive: boolean;
    deployedAt: BigNumberish;
    deprecatedAt: BigNumberish;
  };

  export type ContractInfoStructOutput = [
    contractAddress: string,
    version: bigint,
    isActive: boolean,
    deployedAt: bigint,
    deprecatedAt: bigint
  ] & {
    contractAddress: string;
    version: bigint;
    isActive: boolean;
    deployedAt: bigint;
    deprecatedAt: bigint;
  };
}

export interface IQuintyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchRegisterContracts"
      | "deprecateContract"
      | "getAllVersions"
      | "getContract"
      | "getContractByVersion"
      | "getContractInfo"
      | "isActive"
      | "isPaused"
      | "registerContract"
      | "setPaused"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractDeprecated"
      | "ContractRegistered"
      | "ProtocolPaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchRegisterContracts",
    values: [BytesLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deprecateContract",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllVersions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContract",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractByVersion",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isActive", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerContract",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;

  decodeFunctionResult(
    functionFragment: "batchRegisterContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deprecateContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllVersions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractByVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
}

export namespace ContractDeprecatedEvent {
  export type InputTuple = [
    contractType: BytesLike,
    version: BigNumberish,
    contractAddress: AddressLike
  ];
  export type OutputTuple = [
    contractType: string,
    version: bigint,
    contractAddress: string
  ];
  export interface OutputObject {
    contractType: string;
    version: bigint;
    contractAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractRegisteredEvent {
  export type InputTuple = [
    contractType: BytesLike,
    contractAddress: AddressLike,
    version: BigNumberish,
    previousAddress: AddressLike
  ];
  export type OutputTuple = [
    contractType: string,
    contractAddress: string,
    version: bigint,
    previousAddress: string
  ];
  export interface OutputObject {
    contractType: string;
    contractAddress: string;
    version: bigint;
    previousAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolPausedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IQuintyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IQuintyRegistry;
  waitForDeployment(): Promise<this>;

  interface: IQuintyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchRegisterContracts: TypedContractMethod<
    [contractTypes: BytesLike[], contractAddresses: AddressLike[]],
    [void],
    "nonpayable"
  >;

  deprecateContract: TypedContractMethod<
    [contractType: BytesLike, version: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllVersions: TypedContractMethod<
    [contractType: BytesLike],
    [string[]],
    "view"
  >;

  getContract: TypedContractMethod<[contractType: BytesLike], [string], "view">;

  getContractByVersion: TypedContractMethod<
    [contractType: BytesLike, version: BigNumberish],
    [string],
    "view"
  >;

  getContractInfo: TypedContractMethod<
    [contractType: BytesLike],
    [IQuintyRegistry.ContractInfoStructOutput],
    "view"
  >;

  isActive: TypedContractMethod<[contractType: BytesLike], [boolean], "view">;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  registerContract: TypedContractMethod<
    [contractType: BytesLike, contractAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[paused: boolean], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchRegisterContracts"
  ): TypedContractMethod<
    [contractTypes: BytesLike[], contractAddresses: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deprecateContract"
  ): TypedContractMethod<
    [contractType: BytesLike, version: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllVersions"
  ): TypedContractMethod<[contractType: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getContract"
  ): TypedContractMethod<[contractType: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getContractByVersion"
  ): TypedContractMethod<
    [contractType: BytesLike, version: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractInfo"
  ): TypedContractMethod<
    [contractType: BytesLike],
    [IQuintyRegistry.ContractInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[contractType: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerContract"
  ): TypedContractMethod<
    [contractType: BytesLike, contractAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[paused: boolean], [void], "nonpayable">;

  getEvent(
    key: "ContractDeprecated"
  ): TypedContractEvent<
    ContractDeprecatedEvent.InputTuple,
    ContractDeprecatedEvent.OutputTuple,
    ContractDeprecatedEvent.OutputObject
  >;
  getEvent(
    key: "ContractRegistered"
  ): TypedContractEvent<
    ContractRegisteredEvent.InputTuple,
    ContractRegisteredEvent.OutputTuple,
    ContractRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolPaused"
  ): TypedContractEvent<
    ProtocolPausedEvent.InputTuple,
    ProtocolPausedEvent.OutputTuple,
    ProtocolPausedEvent.OutputObject
  >;

  filters: {
    "ContractDeprecated(bytes32,uint256,address)": TypedContractEvent<
      ContractDeprecatedEvent.InputTuple,
      ContractDeprecatedEvent.OutputTuple,
      ContractDeprecatedEvent.OutputObject
    >;
    ContractDeprecated: TypedContractEvent<
      ContractDeprecatedEvent.InputTuple,
      ContractDeprecatedEvent.OutputTuple,
      ContractDeprecatedEvent.OutputObject
    >;

    "ContractRegistered(bytes32,address,uint256,address)": TypedContractEvent<
      ContractRegisteredEvent.InputTuple,
      ContractRegisteredEvent.OutputTuple,
      ContractRegisteredEvent.OutputObject
    >;
    ContractRegistered: TypedContractEvent<
      ContractRegisteredEvent.InputTuple,
      ContractRegisteredEvent.OutputTuple,
      ContractRegisteredEvent.OutputObject
    >;

    "ProtocolPaused(bool)": TypedContractEvent<
      ProtocolPausedEvent.InputTuple,
      ProtocolPausedEvent.OutputTuple,
      ProtocolPausedEvent.OutputObject
    >;
    ProtocolPaused: TypedContractEvent<
      ProtocolPausedEvent.InputTuple,
      ProtocolPausedEvent.OutputTuple,
      ProtocolPausedEvent.OutputObject
    >;
  };
}
