/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface LookingForGrantInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelRequest"
      | "createFundingRequest"
      | "fundingRequests"
      | "getAvailableFunds"
      | "getRequestInfo"
      | "getSupporter"
      | "getSupporterContribution"
      | "getSupporterCount"
      | "getUpdate"
      | "getUpdateCount"
      | "nftAddress"
      | "owner"
      | "postUpdate"
      | "renounceOwnership"
      | "requestCounter"
      | "setNFTAddress"
      | "supportRequest"
      | "transferOwnership"
      | "updateProjectInfo"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundingRequestCreated"
      | "FundsWithdrawn"
      | "OwnershipTransferred"
      | "RequestCancelled"
      | "RequestFunded"
      | "SupportReceived"
      | "UpdatePosted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createFundingRequest",
    values: [string, string, string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundingRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupporter",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupporterContribution",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupporterCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUpdate",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUpdateCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nftAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postUpdate",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setNFTAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProjectInfo",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createFundingRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupporterContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupporterCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUpdate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUpdateCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nftAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postUpdate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNFTAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProjectInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace FundingRequestCreatedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    requester: AddressLike,
    title: string,
    fundingGoal: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    requester: string,
    title: string,
    fundingGoal: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    requester: string;
    title: string;
    fundingGoal: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    requester: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    requester: string,
    amount: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    requester: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestCancelledEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestFundedEvent {
  export type InputTuple = [requestId: BigNumberish, totalRaised: BigNumberish];
  export type OutputTuple = [requestId: bigint, totalRaised: bigint];
  export interface OutputObject {
    requestId: bigint;
    totalRaised: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupportReceivedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    supporter: AddressLike,
    amount: BigNumberish,
    totalRaised: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    supporter: string,
    amount: bigint,
    totalRaised: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    supporter: string;
    amount: bigint;
    totalRaised: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatePostedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    author: AddressLike,
    content: string
  ];
  export type OutputTuple = [
    requestId: bigint,
    author: string,
    content: string
  ];
  export interface OutputObject {
    requestId: bigint;
    author: string;
    content: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LookingForGrant extends BaseContract {
  connect(runner?: ContractRunner | null): LookingForGrant;
  waitForDeployment(): Promise<this>;

  interface: LookingForGrantInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelRequest: TypedContractMethod<
    [_requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createFundingRequest: TypedContractMethod<
    [
      _title: string,
      _projectDetails: string,
      _progress: string,
      _socialAccounts: string,
      _offering: string,
      _fundingGoal: BigNumberish,
      _deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  fundingRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        requester: string;
        title: string;
        projectDetails: string;
        progress: string;
        socialAccounts: string;
        offering: string;
        fundingGoal: bigint;
        totalRaised: bigint;
        createdAt: bigint;
        deadline: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getAvailableFunds: TypedContractMethod<
    [_requestId: BigNumberish],
    [bigint],
    "view"
  >;

  getRequestInfo: TypedContractMethod<
    [_requestId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        requester: string;
        title: string;
        projectDetails: string;
        progress: string;
        socialAccounts: string;
        offering: string;
        fundingGoal: bigint;
        totalRaised: bigint;
        createdAt: bigint;
        deadline: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getSupporter: TypedContractMethod<
    [_requestId: BigNumberish, _index: BigNumberish],
    [
      [string, bigint, bigint] & {
        addr: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getSupporterContribution: TypedContractMethod<
    [_requestId: BigNumberish, _supporter: AddressLike],
    [bigint],
    "view"
  >;

  getSupporterCount: TypedContractMethod<
    [_requestId: BigNumberish],
    [bigint],
    "view"
  >;

  getUpdate: TypedContractMethod<
    [_requestId: BigNumberish, _updateId: BigNumberish],
    [
      [string, string, bigint] & {
        author: string;
        content: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getUpdateCount: TypedContractMethod<
    [_requestId: BigNumberish],
    [bigint],
    "view"
  >;

  nftAddress: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  postUpdate: TypedContractMethod<
    [_requestId: BigNumberish, _content: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestCounter: TypedContractMethod<[], [bigint], "view">;

  setNFTAddress: TypedContractMethod<
    [_nftAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  supportRequest: TypedContractMethod<
    [_requestId: BigNumberish],
    [void],
    "payable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateProjectInfo: TypedContractMethod<
    [_requestId: BigNumberish, _projectDetails: string, _progress: string],
    [void],
    "nonpayable"
  >;

  withdrawFunds: TypedContractMethod<
    [_requestId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelRequest"
  ): TypedContractMethod<[_requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createFundingRequest"
  ): TypedContractMethod<
    [
      _title: string,
      _projectDetails: string,
      _progress: string,
      _socialAccounts: string,
      _offering: string,
      _fundingGoal: BigNumberish,
      _deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundingRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        requester: string;
        title: string;
        projectDetails: string;
        progress: string;
        socialAccounts: string;
        offering: string;
        fundingGoal: bigint;
        totalRaised: bigint;
        createdAt: bigint;
        deadline: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAvailableFunds"
  ): TypedContractMethod<[_requestId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRequestInfo"
  ): TypedContractMethod<
    [_requestId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        requester: string;
        title: string;
        projectDetails: string;
        progress: string;
        socialAccounts: string;
        offering: string;
        fundingGoal: bigint;
        totalRaised: bigint;
        createdAt: bigint;
        deadline: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSupporter"
  ): TypedContractMethod<
    [_requestId: BigNumberish, _index: BigNumberish],
    [
      [string, bigint, bigint] & {
        addr: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSupporterContribution"
  ): TypedContractMethod<
    [_requestId: BigNumberish, _supporter: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSupporterCount"
  ): TypedContractMethod<[_requestId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUpdate"
  ): TypedContractMethod<
    [_requestId: BigNumberish, _updateId: BigNumberish],
    [
      [string, string, bigint] & {
        author: string;
        content: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUpdateCount"
  ): TypedContractMethod<[_requestId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "nftAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postUpdate"
  ): TypedContractMethod<
    [_requestId: BigNumberish, _content: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setNFTAddress"
  ): TypedContractMethod<[_nftAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportRequest"
  ): TypedContractMethod<[_requestId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateProjectInfo"
  ): TypedContractMethod<
    [_requestId: BigNumberish, _projectDetails: string, _progress: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<
    [_requestId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FundingRequestCreated"
  ): TypedContractEvent<
    FundingRequestCreatedEvent.InputTuple,
    FundingRequestCreatedEvent.OutputTuple,
    FundingRequestCreatedEvent.OutputObject
  >;
  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RequestCancelled"
  ): TypedContractEvent<
    RequestCancelledEvent.InputTuple,
    RequestCancelledEvent.OutputTuple,
    RequestCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RequestFunded"
  ): TypedContractEvent<
    RequestFundedEvent.InputTuple,
    RequestFundedEvent.OutputTuple,
    RequestFundedEvent.OutputObject
  >;
  getEvent(
    key: "SupportReceived"
  ): TypedContractEvent<
    SupportReceivedEvent.InputTuple,
    SupportReceivedEvent.OutputTuple,
    SupportReceivedEvent.OutputObject
  >;
  getEvent(
    key: "UpdatePosted"
  ): TypedContractEvent<
    UpdatePostedEvent.InputTuple,
    UpdatePostedEvent.OutputTuple,
    UpdatePostedEvent.OutputObject
  >;

  filters: {
    "FundingRequestCreated(uint256,address,string,uint256,uint256)": TypedContractEvent<
      FundingRequestCreatedEvent.InputTuple,
      FundingRequestCreatedEvent.OutputTuple,
      FundingRequestCreatedEvent.OutputObject
    >;
    FundingRequestCreated: TypedContractEvent<
      FundingRequestCreatedEvent.InputTuple,
      FundingRequestCreatedEvent.OutputTuple,
      FundingRequestCreatedEvent.OutputObject
    >;

    "FundsWithdrawn(uint256,address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RequestCancelled(uint256)": TypedContractEvent<
      RequestCancelledEvent.InputTuple,
      RequestCancelledEvent.OutputTuple,
      RequestCancelledEvent.OutputObject
    >;
    RequestCancelled: TypedContractEvent<
      RequestCancelledEvent.InputTuple,
      RequestCancelledEvent.OutputTuple,
      RequestCancelledEvent.OutputObject
    >;

    "RequestFunded(uint256,uint256)": TypedContractEvent<
      RequestFundedEvent.InputTuple,
      RequestFundedEvent.OutputTuple,
      RequestFundedEvent.OutputObject
    >;
    RequestFunded: TypedContractEvent<
      RequestFundedEvent.InputTuple,
      RequestFundedEvent.OutputTuple,
      RequestFundedEvent.OutputObject
    >;

    "SupportReceived(uint256,address,uint256,uint256)": TypedContractEvent<
      SupportReceivedEvent.InputTuple,
      SupportReceivedEvent.OutputTuple,
      SupportReceivedEvent.OutputObject
    >;
    SupportReceived: TypedContractEvent<
      SupportReceivedEvent.InputTuple,
      SupportReceivedEvent.OutputTuple,
      SupportReceivedEvent.OutputObject
    >;

    "UpdatePosted(uint256,address,string)": TypedContractEvent<
      UpdatePostedEvent.InputTuple,
      UpdatePostedEvent.OutputTuple,
      UpdatePostedEvent.OutputObject
    >;
    UpdatePosted: TypedContractEvent<
      UpdatePostedEvent.InputTuple,
      UpdatePostedEvent.OutputTuple,
      UpdatePostedEvent.OutputObject
    >;
  };
}
