/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDisputeResolver,
  IDisputeResolverInterface,
} from "../../../contracts/Quinty.sol/IDisputeResolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_bountyId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_slashAmount",
        type: "uint256",
      },
    ],
    name: "initiateExpiryVote",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDisputeResolver__factory {
  static readonly abi = _abi;
  static createInterface(): IDisputeResolverInterface {
    return new Interface(_abi) as IDisputeResolverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDisputeResolver {
    return new Contract(address, _abi, runner) as unknown as IDisputeResolver;
  }
}
